# lib/gen-codex.sh — Codex generation (config.toml, skills, AGENTS.md)
# Sourced by agent-sync.sh. Do not execute directly.

generate_codex_config() {
    mkdir -p "$PROJECT_DIR/.codex"

    if [ -f "$PROJECT_DIR/.codex/config.toml" ] && [ ! -f "$CODEX_CONFIG_STAMP" ]; then
        _warn "  SKIP: .codex/config.toml exists and is not managed by agent-sync."
        _warn "        To let agent-sync manage it, delete it and re-run."
        return 0
    fi

    cat > "$PROJECT_DIR/.codex/config.toml" <<'TOML'
# Auto-generated by agent-sync. Do not edit manually.
# Allows Codex to discover .agent-rules/AGENTS.md without a root-level symlink.
project_doc_fallback_filenames = [".agent-rules/AGENTS.md"]

[features]
# Renamed from hierarchical_agents (openai/codex PR #9215, 2026-01-14).
# Enables subdirectory AGENTS.md scoping. Not yet in official docs — may change.
child_agents_md = true
TOML

    touch "$CODEX_CONFIG_STAMP"
    echo "  Codex: .codex/config.toml deployed"
}

# Codex skills deployed to .agents/skills/ (repo-scoped discovery path per Codex docs).
generate_codex_skills() {
    deploy_artifacts "$RULES_HOME/skills" "$PROJECT_DIR/.agents/skills" "$CODEX_SKILLS_MANIFEST" "Codex Skills" "dirs"
}

generate_codex() {
    mkdir -p "$PROJECT_DIR/.agent-rules"

    generate_claude

    cp "$PROJECT_DIR/.agent-rules/CLAUDE.md" "$PROJECT_DIR/.agent-rules/AGENTS.md"
    local tmp_agents
    tmp_agents="$(mktemp)"
    sed '1s/.*<!-- Auto-generated.*/<!-- Auto-generated by agent-sync for Codex. Do not edit manually. -->/' \
        "$PROJECT_DIR/.agent-rules/AGENTS.md" > "$tmp_agents" 2>/dev/null \
        && mv "$tmp_agents" "$PROJECT_DIR/.agent-rules/AGENTS.md" \
        || rm -f "$tmp_agents"

    local agents_size
    agents_size=$(wc -c < "$PROJECT_DIR/.agent-rules/AGENTS.md" | tr -d ' ')
    echo "  Codex: AGENTS.md ($agents_size bytes)"
    if [ "$agents_size" -gt 32768 ]; then
        _warn "  WARNING: AGENTS.md exceeds 32KiB ($agents_size bytes). Codex may silently truncate!"
    fi
}
