# lib/gen-opencode.sh — OpenCode generation (opencode.json, skills, subagents)
# Sourced by agent-sync.sh. Do not execute directly.
#
# HIST-006: OpenCode integrates as a fourth native tool alongside Cursor /
# Claude Code / Codex. Native-mode outputs:
#   - opencode.json at project root (instructions globs reuse existing rule
#     files — no second rule compilation, because the same sources already
#     feed Cursor and Claude Code)
#   - .opencode/skills/<prefix><name>/SKILL.md (skill deploy parity with the
#     other tools; prefix behavior from HIST-005)
#   - .opencode/agent/<prefix><name>.md (subagent skeleton — no-op until
#     subagents/opencode/ is populated; see deploy_subagent_files)
#
# Config ownership: opencode.json generated by agent-sync carries a sentinel
# "_generated_by": "agent-sync" marker. A hand-authored opencode.json (no
# marker) is never touched by sync/clean/reconcile — only the marker-gated
# files are managed. This matches the .cursor/worktrees.json pattern.

# Marker line grepped by reconcile/clean to decide ownership. The exact
# string (including surrounding whitespace) is what `grep -q` looks for.
OPENCODE_MARKER='"_generated_by": "agent-sync"'

# Generate opencode.json at project root. Reuses existing rule globs rather
# than assembling a new document; OpenCode globs tolerate missing files so
# CC_MODE=off projects still produce a valid config.
generate_opencode_config() {
    local config="$PROJECT_DIR/opencode.json"
    local template="$RULES_HOME/templates/rule_templates/opencode-rule-template.json"

    if [ ! -f "$template" ]; then
        _warn "  SKIP: opencode-rule-template.json missing at $template"
        return 0
    fi

    if [ -f "$config" ] && ! grep -q "$OPENCODE_MARKER" "$config" 2>/dev/null; then
        _warn "  SKIP: opencode.json exists and is not managed by agent-sync."
        _warn "        To let agent-sync manage it, delete it and re-run."
        return 0
    fi

    # Assemble the instructions array based on the other tools' modes.
    # Cursor rules are always emitted by a full sync, so they are
    # unconditional. CC rules depend on CC_MODE. The overlay file is
    # always referenced when it exists — OpenCode's glob engine no-ops
    # missing paths, but listing it explicitly gives a clearer signal.
    local instructions='".cursor/rules/*.mdc"'
    if [ "${CC_MODE:-native}" != "off" ]; then
        instructions="$instructions, \".claude/rules/*.md\""
    fi
    if [ -f "$PROJECT_DIR/.agent-local.md" ]; then
        instructions="$instructions, \".agent-local.md\""
    fi

    # permission.skill: when a prefix is active, narrow the blanket allow
    # to "${prefix}*" and fall back to "ask" for unrelated skills. Empty
    # prefix means agent-toolkit isn't isolating its namespace, so the
    # template's wildcard allow is preserved.
    local skill_perm
    if [ -n "${SKILL_PREFIX:-}" ]; then
        skill_perm="{\"${SKILL_PREFIX}*\": \"allow\", \"*\": \"ask\"}"
    else
        skill_perm='{"*": "allow"}'
    fi

    # Heredoc must be unquoted so ${instructions} / ${skill_perm} expand;
    # escape the literal JSON $schema key with a backslash.
    cat > "$config" <<JSON
{
    "\$schema": "https://opencode.ai/config.json",
    "_generated_by": "agent-sync",
    "instructions": [${instructions}],
    "permission": {
        "skill": ${skill_perm}
    }
}
JSON

    echo "  OpenCode: opencode.json deployed"
}

# OpenCode skills deployed to .opencode/skills/ (directory-based, same layout
# as .cursor/skills/ and .claude/skills/).
generate_opencode_skills() {
    deploy_artifacts "$RULES_HOME/skills" "$PROJECT_DIR/.opencode/skills" "$OPENCODE_SKILLS_MANIFEST" "OpenCode Skills"
}

# OpenCode subagents deployed to .opencode/agent/ (OpenCode's native
# convention: singular "agent" directory, one *.md per subagent).
# Source: $RULES_HOME/subagents/opencode/<name>.md (not populated yet —
# deploy_subagent_files is a no-op on empty/missing source).
generate_opencode_subagents() {
    deploy_subagent_files "$RULES_HOME/subagents/opencode" "$PROJECT_DIR/.opencode/agent" "$OPENCODE_SUBAGENTS_MANIFEST" "OpenCode Subagents"
}
