# lib/gen-codex.sh — Codex generation (config.toml, skills, AGENTS.md)
# Sourced by agent-sync.sh. Do not execute directly.

generate_codex_config() {
    mkdir -p "$PROJECT_DIR/.codex"

    if [ -f "$PROJECT_DIR/.codex/config.toml" ] && [ ! -f "$CODEX_CONFIG_STAMP" ]; then
        _warn "  SKIP: .codex/config.toml exists and is not managed by agent-sync."
        _warn "        To let agent-sync manage it, delete it and re-run."
        return 0
    fi

    cat > "$PROJECT_DIR/.codex/config.toml" <<'TOML'
# Auto-generated by agent-sync. Do not edit manually.
# Allows Codex to discover .agent-rules/AGENTS.md without a root-level symlink.
project_doc_fallback_filenames = [".agent-rules/AGENTS.md"]

[features]
# Enables subdirectory AGENTS.md walking so Codex picks up sub-repo overlays
# that agent-sync emits as nested AGENTS.md files. Renamed from
# hierarchical_agents in openai/codex PR #9215 (2026-01-14).
#
# Source of truth (verified 2026-04-21):
#   openai/codex @ main — codex-rs/features/src/lib.rs
#   → Feature::ChildAgentsMd, Stage::UnderDevelopment, default_enabled=false
#
# The flag is still opt-in — agents-md docs describe the flag-on behavior,
# NOT the default. Removing this line breaks sub-repo AGENTS.md discovery.
child_agents_md = true
TOML

    touch "$CODEX_CONFIG_STAMP"
    echo "  Codex: .codex/config.toml deployed"
}

# Codex skills deployed to .agents/skills/ (repo-scoped discovery path per Codex docs).
generate_codex_skills() {
    deploy_artifacts "$RULES_HOME/skills" "$PROJECT_DIR/.agents/skills" "$CODEX_SKILLS_MANIFEST" "Codex Skills"
}

# Internal: assemble the monolithic AGENTS.md body (header + core + packs +
# overlay) directly. HIST-004 removed the previous
# "generate_claude → cp CLAUDE.md AGENTS.md → sed swap header" pipeline because
# CLAUDE.md is no longer a produced artifact. The concat logic was migrated
# here verbatim from the old gen-claude.sh::generate_claude.
_build_agents_body() {
    local agents_file="$1"
    echo "<!-- Auto-generated by agent-sync for Codex. Do not edit manually. -->" > "$agents_file"
    echo "" >> "$agents_file"

    local rule_file pack_name
    for rule_file in "$RULES_HOME"/core/*.md; do
        [ -f "$rule_file" ] || continue
        cat "$rule_file" >> "$agents_file"
        echo "" >> "$agents_file"
        echo "---" >> "$agents_file"
        echo "" >> "$agents_file"
    done

    for rule_file in "$RULES_HOME"/packs/*.md; do
        [ -f "$rule_file" ] || continue
        pack_name="$(basename "$rule_file" .md)"
        pack_is_active "$pack_name" || continue
        cat "$rule_file" >> "$agents_file"
        echo "" >> "$agents_file"
        echo "---" >> "$agents_file"
        echo "" >> "$agents_file"
    done

    if [ -f "$PROJECT_DIR/.agent-local.md" ]; then
        strip_html_comments < "$PROJECT_DIR/.agent-local.md" >> "$agents_file"
        echo "" >> "$agents_file"
    fi
}

generate_codex() {
    mkdir -p "$PROJECT_DIR/.agent-rules"
    local agents_file="$PROJECT_DIR/.agent-rules/AGENTS.md"
    _build_agents_body "$agents_file"

    local agents_size
    agents_size=$(wc -c < "$agents_file" | tr -d ' ')
    echo "  Codex: AGENTS.md ($agents_size bytes)"
    if [ "$agents_size" -gt 32768 ]; then
        _warn "  WARNING: AGENTS.md exceeds 32KiB ($agents_size bytes). Codex may silently truncate!"
    fi
}
