# lib/sync.sh — Mode reconciliation, sub-repo sync, cleanup remnants
# Sourced by agent-sync.sh. Do not execute directly.

# HIST-003 orphan (GPT-5.4 M1 refinement): pre-refactor agent-sync deployed CC
# commands via deploy_artifacts in "files" mode and recorded each filename in
# .agent-sync-commands-manifest. We now clean **only** the files listed in that
# manifest, then the manifest itself, then attempt rmdir (which succeeds only
# if the directory is empty — i.e. user added no files of their own).
#
# Ownership matrix:
#   (a) No manifest present            → no-op (user-authored commands/, honored)
#   (b) Manifest present, no user adds → all listed files + manifest removed,
#                                         directory removed cleanly
#   (c) Manifest present, user added   → listed files + manifest removed, but
#                                         user-added files (and containing dir)
#                                         preserved
#
# Fresh projects (never had agent-sync-managed commands) are always case (a),
# so this is a no-op for them. Also called from do_clean() in clean.sh and
# from the cc / cc-rules / cc-skills subcommands in agent-sync.sh.
cleanup_legacy_cc_commands() {
    local commands_dir="$PROJECT_DIR/.claude/commands"
    local stamp="$commands_dir/.agent-sync-commands-manifest"
    [ -f "$stamp" ] || return 0

    local removed=0 item
    while IFS= read -r item; do
        [ -z "$item" ] && continue
        if [ -e "$commands_dir/$item" ]; then
            rm -f "$commands_dir/$item"
            removed=$((removed + 1))
        fi
    done < "$stamp"

    rm -f "$stamp"

    # rmdir succeeds only when the directory is empty — i.e. the user did not
    # add any of their own files. Failure here is the mixed-ownership case and
    # is intentionally silent; we keep user content untouched.
    if rmdir "$commands_dir" 2>/dev/null; then
        echo "  Removed legacy .claude/commands/ ($removed file(s) decommissioned, HIST-003)"
    else
        echo "  Removed $removed agent-sync-managed file(s) from .claude/commands/ (user-added files preserved, HIST-003)"
    fi
}

# Remove artifacts from modes that are now disabled (convergent sync).
reconcile_mode_outputs() {
    # Always opportunistic: decommissioned subsystems never come back, so we
    # can clean their remnants regardless of CC_MODE.
    cleanup_legacy_cc_commands

    if [ "$CC_MODE" = "off" ]; then
        if [ -f "$CC_RULES_MANIFEST" ] || [ -f "$CC_SKILLS_MANIFEST" ]; then
            echo "  Reconciling CC Mode=off: removing .claude/ artifacts..."
            clean_manifest "$CC_RULES_MANIFEST" "$PROJECT_DIR/.claude/rules" "files"
            rmdir "$PROJECT_DIR/.claude/rules" 2>/dev/null || true
            clean_manifest "$CC_SKILLS_MANIFEST" "$PROJECT_DIR/.claude/skills" "dirs"
            rmdir "$PROJECT_DIR/.claude/skills" 2>/dev/null || true
            rmdir "$PROJECT_DIR/.claude" 2>/dev/null || true
        fi
    fi

    if [ "$CODEX_MODE" = "off" ]; then
        rm -f "$PROJECT_DIR/.agent-rules/AGENTS.md"
        if [ -f "$CODEX_CONFIG_STAMP" ]; then
            rm -f "$PROJECT_DIR/.codex/config.toml" "$CODEX_CONFIG_STAMP"
            rmdir "$PROJECT_DIR/.codex" 2>/dev/null || true
        fi
        clean_manifest "$CODEX_SKILLS_MANIFEST" "$PROJECT_DIR/.agents/skills" "dirs"
        rmdir "$PROJECT_DIR/.agents/skills" 2>/dev/null || true
        rmdir "$PROJECT_DIR/.agents" 2>/dev/null || true
    fi

    if [ "$CODEX_MODE" = "legacy" ]; then
        if [ -f "$CODEX_CONFIG_STAMP" ]; then
            rm -f "$PROJECT_DIR/.codex/config.toml" "$CODEX_CONFIG_STAMP"
            rmdir "$PROJECT_DIR/.codex" 2>/dev/null || true
        fi
        clean_manifest "$CODEX_SKILLS_MANIFEST" "$PROJECT_DIR/.agents/skills" "dirs"
        rmdir "$PROJECT_DIR/.agents/skills" 2>/dev/null || true
        rmdir "$PROJECT_DIR/.agents" 2>/dev/null || true
    fi
}

cleanup_remnants() {
    rm -f "$PROJECT_DIR/CLAUDE.md" "$PROJECT_DIR/AGENTS.md"
    # HIST-004: .agent-rules/CLAUDE.md was generated by pre-HIST-004 agent-sync.
    # Proactively remove on every sync so upgrading projects don't keep a stale
    # artifact until the user runs `agent-sync clean`. AGENTS.md lives in the
    # same directory and is still actively managed by reconcile_mode_outputs.
    rm -f "$PROJECT_DIR/.agent-rules/CLAUDE.md"
}

sync_sub_repos() {
    local manifest_new="$MANIFEST.new"
    : > "$manifest_new"

    local sub_overlay sub_dir sub_rel sub_agents mdc_name mdc_target overlay_bytes
    while read -r sub_overlay; do
        sub_dir="$(dirname "$sub_overlay")"
        sub_rel="${sub_dir#"$PROJECT_DIR"/}"

        # HIST-004: sub-repo CLAUDE.md used to be a separate artifact and also
        # acted as the intermediate for AGENTS.md. It's now decommissioned;
        # emit AGENTS.md directly when Codex is enabled, and unconditionally
        # clear any stale CLAUDE.md left by pre-HIST-004 agent-sync runs.
        sub_agents="$sub_dir/AGENTS.md"
        if [ "$CODEX_MODE" != "off" ]; then
            {
                echo "<!-- Auto-generated by agent-sync for Codex (sub-repo overlay only). Do not edit manually. -->"
                echo ""
                strip_html_comments < "$sub_overlay"
            } > "$sub_agents"
        else
            rm -f "$sub_agents"
        fi
        rm -f "$sub_dir/CLAUDE.md"

        mdc_name="$(echo "$sub_rel" | tr '/' '-')-overlay.mdc"
        mdc_target="$PROJECT_DIR/.cursor/rules/$mdc_name"
        {
            echo "---"
            echo "description: ${sub_rel} project overlay"
            echo "globs: ${sub_rel}/**"
            echo "alwaysApply: false"
            echo "---"
            echo ""
            strip_html_comments < "$sub_overlay"
        } > "$mdc_target"

        if [ "$CC_MODE" != "off" ]; then
            local cc_overlay_name cc_overlay_target
            cc_overlay_name="$(echo "$sub_rel" | tr '/' '-')-overlay.md"
            cc_overlay_target="$PROJECT_DIR/.claude/rules/$cc_overlay_name"
            {
                echo "---"
                echo "globs: \"${sub_rel}/**\""
                echo "---"
                echo ""
                strip_html_comments < "$sub_overlay"
            } > "$cc_overlay_target"
        fi

        overlay_bytes=$(wc -c < "$sub_overlay" | tr -d ' ')
        echo "$sub_rel" >> "$manifest_new"
        echo "  Sub-repo $sub_rel: ${mdc_name} + overlays (source $overlay_bytes bytes)"
    done < <(find "$PROJECT_DIR" -mindepth 2 -maxdepth 3 -name '.agent-local.md' -not -path '*/.git/*' -not -path '*/node_modules/*')

    if [ -f "$MANIFEST" ]; then
        local old_rel ghost_mdc ghost_cc
        while IFS= read -r old_rel; do
            if [ ! -f "$PROJECT_DIR/$old_rel/.agent-local.md" ]; then
                rm -f "$PROJECT_DIR/$old_rel/CLAUDE.md" "$PROJECT_DIR/$old_rel/AGENTS.md"
                ghost_mdc="$(echo "$old_rel" | tr '/' '-')-overlay.mdc"
                rm -f "$PROJECT_DIR/.cursor/rules/$ghost_mdc"
                ghost_cc="$(echo "$old_rel" | tr '/' '-')-overlay.md"
                rm -f "$PROJECT_DIR/.claude/rules/$ghost_cc"
                echo "  Cleaned ghost rules: $old_rel/ (overlay removed)"
            fi
        done < "$MANIFEST"
    fi
    mv "$manifest_new" "$MANIFEST"
}
