# lib/sync.sh — Mode reconciliation, sub-repo sync, cleanup remnants
# Sourced by agent-sync.sh. Do not execute directly.

# Remove artifacts from modes that are now disabled (convergent sync).
reconcile_mode_outputs() {
    if [ "$CC_MODE" = "off" ]; then
        if [ -f "$CC_RULES_MANIFEST" ] || [ -f "$CC_SKILLS_MANIFEST" ] || [ -f "$CC_COMMANDS_MANIFEST" ]; then
            echo "  Reconciling CC Mode=off: removing .claude/ artifacts..."
            clean_manifest "$CC_RULES_MANIFEST" "$PROJECT_DIR/.claude/rules" "files"
            rmdir "$PROJECT_DIR/.claude/rules" 2>/dev/null || true
            clean_manifest "$CC_SKILLS_MANIFEST" "$PROJECT_DIR/.claude/skills" "dirs"
            rmdir "$PROJECT_DIR/.claude/skills" 2>/dev/null || true
            clean_manifest "$CC_COMMANDS_MANIFEST" "$PROJECT_DIR/.claude/commands" "files"
            rmdir "$PROJECT_DIR/.claude/commands" 2>/dev/null || true
            rmdir "$PROJECT_DIR/.claude" 2>/dev/null || true
        fi
    fi

    if [ "$CODEX_MODE" = "off" ]; then
        rm -f "$PROJECT_DIR/.agent-rules/AGENTS.md"
        if [ -f "$CODEX_CONFIG_STAMP" ]; then
            rm -f "$PROJECT_DIR/.codex/config.toml" "$CODEX_CONFIG_STAMP"
            rmdir "$PROJECT_DIR/.codex" 2>/dev/null || true
        fi
        clean_manifest "$CODEX_SKILLS_MANIFEST" "$PROJECT_DIR/.agents/skills" "dirs"
        rmdir "$PROJECT_DIR/.agents/skills" 2>/dev/null || true
        rmdir "$PROJECT_DIR/.agents" 2>/dev/null || true
    fi

    if [ "$CODEX_MODE" = "legacy" ]; then
        if [ -f "$CODEX_CONFIG_STAMP" ]; then
            rm -f "$PROJECT_DIR/.codex/config.toml" "$CODEX_CONFIG_STAMP"
            rmdir "$PROJECT_DIR/.codex" 2>/dev/null || true
        fi
        clean_manifest "$CODEX_SKILLS_MANIFEST" "$PROJECT_DIR/.agents/skills" "dirs"
        rmdir "$PROJECT_DIR/.agents/skills" 2>/dev/null || true
        rmdir "$PROJECT_DIR/.agents" 2>/dev/null || true
    fi
}

cleanup_remnants() {
    rm -f "$PROJECT_DIR/CLAUDE.md" "$PROJECT_DIR/AGENTS.md"
}

sync_sub_repos() {
    local manifest_new="$MANIFEST.new"
    : > "$manifest_new"

    local sub_overlay sub_dir sub_rel sub_claude mdc_name mdc_target
    while read -r sub_overlay; do
        sub_dir="$(dirname "$sub_overlay")"
        sub_rel="${sub_dir#"$PROJECT_DIR"/}"

        sub_claude="$sub_dir/CLAUDE.md"
        echo "<!-- Auto-generated by agent-sync (sub-repo overlay only). Do not edit manually. -->" > "$sub_claude"
        echo "" >> "$sub_claude"
        strip_html_comments < "$sub_overlay" >> "$sub_claude"

        if [ "$CODEX_MODE" != "off" ]; then
            cp "$sub_claude" "$sub_dir/AGENTS.md"
        else
            rm -f "$sub_dir/AGENTS.md"
        fi

        mdc_name="$(echo "$sub_rel" | tr '/' '-')-overlay.mdc"
        mdc_target="$PROJECT_DIR/.cursor/rules/$mdc_name"
        {
            echo "---"
            echo "description: ${sub_rel} project overlay"
            echo "globs: ${sub_rel}/**"
            echo "alwaysApply: false"
            echo "---"
            echo ""
            strip_html_comments < "$sub_overlay"
        } > "$mdc_target"

        if [ "$CC_MODE" != "off" ]; then
            local cc_overlay_name cc_overlay_target
            cc_overlay_name="$(echo "$sub_rel" | tr '/' '-')-overlay.md"
            cc_overlay_target="$PROJECT_DIR/.claude/rules/$cc_overlay_name"
            {
                echo "---"
                echo "globs: \"${sub_rel}/**\""
                echo "---"
                echo ""
                strip_html_comments < "$sub_overlay"
            } > "$cc_overlay_target"
        fi

        echo "$sub_rel" >> "$manifest_new"
        echo "  Sub-repo $sub_rel: CLAUDE.md + ${mdc_name} (overlay only, $(wc -c < "$sub_claude" | tr -d ' ') bytes)"
    done < <(find "$PROJECT_DIR" -mindepth 2 -maxdepth 3 -name '.agent-local.md' -not -path '*/.git/*' -not -path '*/node_modules/*')

    if [ -f "$MANIFEST" ]; then
        local old_rel ghost_mdc ghost_cc
        while IFS= read -r old_rel; do
            if [ ! -f "$PROJECT_DIR/$old_rel/.agent-local.md" ]; then
                rm -f "$PROJECT_DIR/$old_rel/CLAUDE.md" "$PROJECT_DIR/$old_rel/AGENTS.md"
                ghost_mdc="$(echo "$old_rel" | tr '/' '-')-overlay.mdc"
                rm -f "$PROJECT_DIR/.cursor/rules/$ghost_mdc"
                ghost_cc="$(echo "$old_rel" | tr '/' '-')-overlay.md"
                rm -f "$PROJECT_DIR/.claude/rules/$ghost_cc"
                echo "  Cleaned ghost rules: $old_rel/ (overlay removed)"
            fi
        done < "$MANIFEST"
    fi
    mv "$manifest_new" "$MANIFEST"
}
